modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/dhyces/trimmed/issues"
[[mods]]
modId="trimmed"
version="${file.jarVersion}"
displayName="Trimmed"
displayURL="https://modrinth.com/mod/trimmed"
logoFile="icon.png"
credits=""
authors="Dhyces"
description='''Better item overrides! Better trim support! Override it all!'''
[[dependencies.trimmed]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trimmed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
