# Mod options
mod_name=Trimmed
mod_id=trimmed
group=dev.dhyces.trimmed
authors=dhyces
version=4.0.1

at_enabled=true
common_mixin_enabled=true
fabric_mixin_enabled=true
neoforge_mixin_enabled=true

# Publishing
publish_debug = false
publish_type = release
modrinth_project_id = q8k4zHw5
curseforge_project_id = 857036

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false