[versions]
minecraft_release = "1.21.3"
minecraft_range = "[1.21.3,1.21.4)"
publish_range = "1.21.3"

parchment_release = "2024.07.28"
parchment_minecraft = "1.21"

javafml_range = "[3,)"
neoforge_release = "21.3.16-beta"
neoforge_range = "[21.3.16-beta,21.4-beta)"

fabric_loader = "0.16.9"
fabric_api_release = "0.107.3+1.21.3"
fabric_api_range = "[0.107.3,)"

mixin = "0.8.7"
mixinextras = "0.4.1"

jetbrains_annotations = "24.1.0"

moddev = "2.0.42-beta"
loom = "1.8.+"
mdg_release = "2.0.0-beta.30"

curseforgegradle = "1.1.25"
minotaur = "2.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft_release" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge_release" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api_release" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixinextras_common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }

[plugins]
mdg = { id = "org.groovymc.modsdotgroovy", version.ref = "mdg_release" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
loom = { id = "fabric-loom", version.ref = "loom" }
curseforgegradle = { id = "net.darkhax.curseforgegradle", version.ref = "curseforgegradle" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }