plugins {
    id 'idea'
    id "shared.conventions"
    alias(libs.plugins.mdg)
    alias(libs.plugins.moddev)
}

base {
    archivesName = "${mod_name}-common-${libs.versions.minecraft.release.get()}"
}

modsDotGroovy {
    multiplatform {
        gather {
            projectProperty("mod_id")
            projectProperty("mod_name")
            projectProperty("authors")
            projectProperty("version")
            projectProperty("at_enabled")
            projectProperty("common_mixin_enabled")
            projectProperty("fabric_mixin_enabled")
            projectProperty("neoforge_mixin_enabled")
        }
        expose()
    }
}

sourceSets {
    api {
        compileClasspath += main.compileClasspath
    }
    main {
        compileClasspath += api.compileClasspath + api.output
        runtimeClasspath += api.runtimeClasspath + api.output
        resources.srcDir 'src/generated/resources'
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
    testCompileOnly.extendsFrom(compileOnly)
}

neoForge {
    // https://projects.neoforged.net/neoforged/neoform
    neoFormVersion = "1.21.3-20241023.131943"

    parchment {
        minecraftVersion = libs.versions.parchment.minecraft.get()
        mappingsVersion = libs.versions.parchment.release.get()
    }

    if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers.from file("src/main/resources/META-INF/accesstransformer.cfg")
    }
}

java {
    registerFeature("api") {
        usingSourceSet(sourceSets.api)
    }
}

dependencies {
    compileOnly libs.mixin
    annotationProcessor libs.mixinextras.common
    compileOnly libs.mixinextras.common
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonJava sourceSets.api.java.sourceDirectories.singleFile
    sourceSets.main.resources.sourceDirectories.forEach {
        commonResources it
    }
}